### ISSUE TITLE
IDE blocks when code coll. username/password combination is incorrect

### ISSUE THREAD

**Issue by cpjvelde** [GunoH/intelliccollab#12]
[DESCRIPTION]
When your code coll. username/password combination is incorrect, the guest-IDE blocks.
In the host-IDE, I get the following prompt:

Collaborator client credentials invalid.  Please supply a valid password.
>

I can then enter a password on stdin. When I enter my correct password in the host-IDE, the guest-IDE continues.

[ANALYSIS]
The call to getServerBuild() seems to cause this problem. Maybe we need to use some other method first to check whether the user's credentials are correct.

LoginTask.run()
-> LoginUtils.login()
	-> LogonUtils.establishEngineConnection(IGlobalOptions,ICollabClientInterface)
		-> LogonUtils.establishEngineConnection(XmlRpcClientConfig)
			-> Engine.getServerBuild()

**Comment by GunoH** [comment]
This only happens on the 9300 branch, with the new Collaborator client libraries.

**Comment by GunoH** [comment]
Let's just overwrite CommandLineClient.askUserPassword() and return an empty String. It will then give up after three tries.
